apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-db
spec:
  ports:
  - name: tcp-db
    port: 5432
    targetPort: postgresql
  selector:
    app: {{ .Values.appName }}-db
  type: ClusterIP
